# Generated by Django 5.1.3 on 2025-03-10 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_location_delete_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="code",
            new_name="id",
        ),
    ]
