# Generated by Django 5.1.3 on 2025-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_rename_code_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
