# Generated by Django 5.1.3 on 2025-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="dateEnd",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="dateIni",
            field=models.DateTimeField(null=True),
        ),
    ]
