# Generated by Django 5.1.3 on 2025-03-14 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_dateend_alter_event_dateini"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="dateEnd",
            new_name="date_end",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="dateIni",
            new_name="date_ini",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="infoTickets",
            new_name="info_tickets",
        ),
    ]
