# Generated by Django 5.1.3 on 2025-03-15 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_rename_dateend_event_date_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                null=True,
                related_name="attended_events",
                through="events.UserEvent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
