# Generated by Django 5.1.3 on 2025-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_event_attendees_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=400),
        ),
    ]
