# Generated by Django 5.1.3 on 2025-03-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_event_title"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX IF EXISTS events_event_code_1d888711_like;",
            reverse_sql="CREATE INDEX events_event_code_1d888711_like ON events_event USING btree (code varchar_pattern_ops);",
        ),
        migrations.AddField(
            model_name="event",
            name="code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
