# Generated by Django 5.2 on 2025-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_rename_image_eventimage_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventimage",
            name="s3_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventimage",
            name="s3_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
