# Generated by Django 5.2 on 2025-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_eventimage_s3_key_eventimage_s3_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlink",
            name="link",
            field=models.URLField(max_length=500),
        ),
    ]
