# Generated by Django 5.2 on 2025-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_alter_eventlink_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventimage",
            name="s3_key",
        ),
        migrations.RemoveField(
            model_name="eventimage",
            name="s3_url",
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
