# Generated by Django 5.2.1 on 2025-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_userreportedevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreportedevent",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
