# Generated by Django 5.2.1 on 2025-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("private_rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateroom",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
