# Generated by Django 5.2.1 on 2025-05-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_remove_eventimage_s3_key_remove_eventimage_s3_url_and_more"),
        ("private_rooms", "0002_privateroom_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateRoomEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "private_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="private_rooms.privateroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("private_room", "event")},
            },
        ),
        migrations.AddField(
            model_name="privateroom",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="private_room_events",
                through="private_rooms.PrivateRoomEvent",
                to="events.event",
            ),
        ),
        migrations.CreateModel(
            name="PrivateRoomVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "private_room_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="private_rooms.privateroomevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("private_room_event", "participant")},
            },
        ),
    ]
