# Generated by Django 5.1.3 on 2025-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="town",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="town",
            unique_together={("name", "region")},
        ),
    ]
