# Generated by Django 5.1.3 on 2025-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_town_name_alter_town_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="location",
            name="space",
            field=models.CharField(max_length=400),
        ),
    ]
