# Generated by Django 5.1.3 on 2025-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_alter_location_address_alter_location_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="space",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
