# Generated by Django 5.1.3 on 2025-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_alter_location_address_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="space",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="town",
            name="name",
            field=models.CharField(max_length=300),
        ),
    ]
