# Generated by Django 5.2.1 on 2025-05-25 19:06

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_notification_userfcmtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.models.user_profile_image_path,
            ),
        ),
    ]
