# Generated by Django 5.2.1 on 2025-05-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
